[package]
name = "martian-robots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
itertools = "0.10.3"

[dev-dependencies]
rstest = "0.12.0"
assert_matches = "1.5.0"